name: flakka_journal
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  fpdart:
    git:
      url: https://github.com/SandroMaglione/fpdart
      ref: effect-refactor
      path: packages/fpdart
  objectbox: ^4.0.0
  stash:
  stash_file:
  stash_memory:
  uuid:

dev_dependencies:
  build_runner: ^2.4.9
  mocktail: ^1.0.3
  objectbox_generator: ^4.0.0
  test: ^1.25.2
  very_good_analysis: ^5.1.0
